### ISSUE TITLE
Terraform Infrastrucutre Automation: Stage 1, Simple EC2 Instance

### ISSUE THREAD

**Issue by Abishtu** [Abishtu/CSSE6400-Ticket-Overflow#1]
# Introduction

Make Terraform and bash script/s to automate the deployment of the application to a very simple monolithic EC2 instance, this will essentially mimic executing the application locally using `docker-compose up --build` but in a remote EC2 instance in the AWS cloud. 

This initial version will focus on having the application deployed to the cloud rather than achieving a micro-services architecture, that will be done with ECS clusters once this is working.

# Tasks

- [x] Read from AWS IAM user access key files and use these for instance.

- [x] EC2 instance created

- [x] Docker and docker compose plugin installed on instance

- [x] Can run base application with `docker-compose` using DynamoDB local in the instance.

- [ ] Can connect with proper instance of DynamoDB

# External Resources

- [Integration of AWS, Terraform, and GitHub for Automated Deployment Infrastructure](https://akshayavb99.medium.com/integration-of-aws-terraform-and-github-for-automated-deployment-infrastructure-da0a19ff4e86)
